# Generated by Django 3.2.8 on 2021-10-29 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='default_profile_picture',
        ),
    ]
