# Generated by Django 3.2.8 on 2021-10-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=254, null=True)),
                ('product', models.CharField(blank=True, max_length=254, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, max_length=254, null=True)),
                ('serving', models.CharField(blank=True, max_length=254, null=True)),
                ('adjustable', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
